PunishXIV/Splatoon

Splatoon/Modules/HTTPServer.cs
Modify the response header of the Splatoon Web API by adjusting the `Access-Control-Allow-Origin` and `Access-Control-Allow-Methods` fields, thus allowing CORS. This is necessary as the CORS policy is currently blocking access to the Web API via a Chromium client.
=> Modify response header in Web API to allow for CORS capabilities.

Splatoon/Gui/CGuiGeneralSettings.cs, Splatoon/Memory/AttachedInfo.cs, Splatoon/Serializables/Configuration.cs
Add a config to output object position in the casting information log lines.
=> Add a config to output object position in logs

Splatoon/Modules/Loader.cs
Correctly removes the load event from the correct framework object, preventing log spam where it loops over and over infinitely.
=> Fix loading spam message in log

SplatoonScripts/Duties/Endwalker/DSR Towers.cs
This marks the towers according to this (https://ff14.toolboxgaming.space/?id=226768720878561&preview=1) strat from the LPDU discord.
It marks the tower the meteor runner should take green (or red if you don't actually have the meteor) and outer/inner towers in a configurable color.
There is also (default off) support to make a callout for the raidgroup because my caller told me it is exhausting to stare at the pattern but I can of course remove that if you don't like it.
=> DSR P2 Sanctity of the Ward Marks for LPDU Strat

SplatoonScripts/Duties/Endwalker/DSR Wrath.cs
This script adds a blue line to follow during P5 Wrath. It shows the correct spots to go to with both Tethers, Blue Marker, Green Marker.
In the case of absolutely no marker it only points to the correct side, spreading is left to the player/party members.
Furthermore it shows danger zones for the tethered charges for players that do not have the specific tether (the radius of the square is guessed, should be kind of accurate)
=> DSR P5 add support for dynamic navigation in Wrath of the Heavens

SplatoonScripts/Duties/Endwalker/DSR Towers.cs
This fixes the take/don't take tower marker, after having meteor the first time it will otherwise always tell you to get the meteor tower.
=> Fix reset behaviour

Splatoon/Gui/CGuiGeneralSettings.cs, Splatoon/Serializables/DisplayStyle.cs, Splatoon/Serializables/Element.cs, Splatoon/Serializables/MechanicType.cs, Splatoon/Structures/DisplayObjectInterfaces.cs, Splatoon/Utils/Colors.cs, Splatoon/Utils/SImGuiEx.cs, Splatoon/Utils/Static.cs
By default, fill will use the stroke color with its alpha multiplied by some intensity.
Fill colors can now only be chosen directly with an override flag.
=> Add new default fill coloring system

Splatoon/Serializables/Element.cs
Fill intensity is the fraction of the element's alpha to used as fill alpha. I was computing the target alpha value and dividing by 255 which makes migrated values overly transparent. The correct divisor is the element's alpha.
=> Fix transparency bug in migration for fill intensity

Splatoon/Gui/CGuiGeneralSettings.cs, Splatoon/Gui/OverlayGui.cs, Splatoon/Serializables/Configuration.cs, Splatoon/Splatoon.cs, Splatoon/Structures/DisplayObjectInterfaces.cs
When i was testing the code, i noticed that when e.FaceMe == true, the sector is growing clockwise, and when e.FaceMe == false, the sector is growing counterclockwise. 
For example, in the case where the angle of the element is set to -10 ~ 50 and the facing target stands at 0-degree direction, the sector drawn is reversed when e.FaceMe is different. 
I don't know if this is intentional, so I only implemented the e.type==5 case.
=> added drawing of filled cone for element.type==5

Splatoon/Gui/Layouts/Elements/LayoutDrawElement.cs, Splatoon/Serializables/Element.cs, Splatoon/Splatoon.cs
A nice to have that eliminates the need to load a Script (Generic/QuestHighlighter, in this case) to target GameObject->NamePlateIconId.
=> Add NamePlateIconId as a targettable attribute for Layouts.

Splatoon/Gui/OverlayGui.cs
Fixes using multi-monitor mode in dalamud drawing the overlay in the wrong position.
=> Fix multi-monitor mode offset issue

SplatoonScripts/Duties/Dawntrail/R4S Replica Wing and Line.cs, SplatoonScripts/update.csv
Add Scripts R4S Replica Wing and Line
=> Add Scripts R4S Replica Wing and Line

Splatoon/Memory/AttachedInfo.cs, Splatoon/SplatoonScripting/ScriptingProcessor.cs, Splatoon/SplatoonScripting/SplatoonScript.cs, SplatoonScripts/Tests/CastStartingTest.cs
I added it because I was the one who suggested it.
I want to get the same clone with a different event handler than OnMessage, for example, the one that appears in the tag match of R3S. Since the clone can only be identified by GameObjectID, I wanted to add it because IBattleChara was needed.
=> [add] Added OnStartingCast(IBattleChara battleChar, uint castId) event methods for Script.

Splatoon/Memory/AttachedInfo.cs, Splatoon/SplatoonScripting/ScriptingProcessor.cs, Splatoon/SplatoonScripting/SplatoonScript.cs, SplatoonScripts/Tests/CastStartingTest.cs
Limiana said it was fine to leave it as is, but I was concerned about the danger and lack of consistency, so I modified it to pass the EntityID as a uint, just like the other methods.
=> [fix] Fix dangerous code

Splatoon/Memory/AttachedInfo.cs, Splatoon/SplatoonScripting/ScriptingProcessor.cs, Splatoon/SplatoonScripting/SplatoonScript.cs, SplatoonScripts/Duties/Dawntrail/R2S Venom Love Pair Split.cs
A problem occurred due to a null reference, so it was fixed and improved.
- OnMessage() is called frequently, so it was changed to OnStartingCast() to reduce processing.
- OnUpdate() is called every tick, so the processing was moved to OnActionEffectEvent() to reduce processing.
- Changed to refer to set instead of Player.Object, and strictly checks whether set and set.action are null, so null reference errors do not occur.
- OnVfx() can also be integrated with OnActionEffectEvent(), so it was changed to process with OnActionEffectEvent().
- Corrected the typo that said "target" as the argument to OnStartingCast should be "source."
- Changed the argument to OnStartingCast to pass DataID instead of EntityID as the argument to sourceID.
=> [fix] R2S scripting improvements

Presets/Dawntrail/Dungeons/93 - Worqor Zormor.md
Updated presets for Ryoqor Terteh which freezes and draws the unsafe delayed AOE.
Updated presets for Kahderyo which draws Unsafe spots for Earthen Shot,Wind shot and Towers. It also draws the unsafe spots for Earthen Shot 2 as they are yellow and particularly hard to see.
Updated presets for Gurgurlur which draws unsafe zones on the wind and directional arrow. It also draws the unsafe first tile which blows up first, which is useful for a later knockback mechanic to avoid it.
=> Create 93 - Worqor Zormor.md

SplatoonScripts/Duties/Dawntrail/R4S Electrope Edge.cs
Support EE2 for different strategies.
Fixed to be able to select the position of the pair by the combination of all Hits and debuff lengths.
I am concerned that since we have changed the data type of the config, it will affect those who are already using it.
I'll test it and if it's ok, I'll switch to regular PR.
=> Support EE2 for different strate.

Splatoon/Gui/Layouts/CGuiLayouts.cs
As the title describes, it sorts everything alphabetically.
=> Add a sort button to the layout menu

Presets/Stormblood/Duties/Ultimate - The Unending Coil of Bahamud.md, SplatoonScripts/Duties/Stormblood/UCOB Twisters.cs, SplatoonScripts/update.csv
The script adds yellow circles to all party members so you can predetermine where twisters might land.
Once they appear the script's circles vanish and the layout draws red warnings around them until they disappear.
Thank you to Discord user EnjoyingTofu for help with the layout
=> UCOB Twintania Twisters Add a script and a preset

SplatoonScripts/Duties/Dawntrail/The Futures Rewritten/P2 Light Rampant JP.cs
to avoid any confusing time, if the player has to bait the aoe, the script will be "turned off" - the player has to know where he/she has to be.
=> Disable drawing if player has AoE to bait and dont need to form any thing

SplatoonScripts/Duties/Dawntrail/The Futures Rewritten/P2 Mirror Mirror.cs
It's more helpful to see where it's safe to go under the mirror than a simple circle in front of the mirror.
=> FRU P2 Mirror Mirror - Make marker a donut corresponding to the mirror cleave

Splatoon/RenderEngines/DirectX11/DirectX11Scene.cs, Splatoon/RenderEngines/ImGuiLegacy/ImGuiLegacyScene.cs
Most overlays already have this flag, but it was missing from some.
=> Add ImGuiWindowFlags.NoFocusOnAppearing to more overlays

Splatoon/RenderEngines/DirectX11/DirectX11Scene.cs, Splatoon/RenderEngines/ImGuiLegacy/ImGuiLegacyScene.cs
No be perfectly honest, I don't know if this change is correct or not. If not, feel free to close this.
It seemed to me that there is no need to incur renderer setup overhead if there are no objects we actually want to draw. Skipping those significantly reduces the impact of having Splatoon running in cases where there are no actual objects to draw.
=> Skip render set up if there's nothing to render

SplatoonScripts/Duties/Stormblood/UCOB dragon baits.cs
N dragon spawns at Position: -0.015319824 0 -24.002502 but the current implementation assumes that N would be at x:0 y:0. This hardcodes it so that N begins at -0.015319824 0 -24.002502 and adjusts from there
=> Fix dragon ordering

SplatoonScripts/Duties/Endwalker/Dragonsong's Reprise/P2 Sanctity Of The Ward First.cs
garume's priority implementation could not retrieve the priority member's name and returned an empty string, this now is able to read the partnered member and flex off them correctly.
=> fixed get priority player

SplatoonScripts/Duties/Endwalker/The Omega Protocol/Program Loop.cs
Update the script to use the Priority Data functions instead thereby following the conga priority of H1-R1-M1-MT-OT-M2-R2-H2 where for example MT flexes from left to right H1/R1/M1 and OT flexes from right to left H2/R2/M2. Follows the same setup that NA uses to prioritise positioning as all mechs are completed using the same conga priority
=> Update script with Priority Data

SplatoonScripts/Duties/Endwalker/The Omega Protocol/Program Loop Priority
Fixed Priority list being only read when Settings UI is drawn As mentioned in DMs, created a separate script in order to rollback the other one so that both can be used.
=> Program Loop Priority
