PunishXIV/Splatoon

SplatoonScripts/Duties/Endwalker/P12S Caloric Theory.cs, SplatoonScripts/Duties/Endwalker/P12S Superchain.cs
Added a config to the Superchain.cs, make the screen cleaner.
Added a script of Caloric Theory mechanic.
=> update some p12s scripts

Presets/Endwalker content/Duties/Pandaemonium 12-1 Savage.md, SplatoonScripts/Duties/Endwalker/P12S Tethers.cs
=> Add P12S Tether Script

Presets/Endwalker content/Duties/Mount Rokkon(Normal&Savage).md
some fixes. please check changelog.
=> Update Mount Rokkon(Normal&Savage).md

Splatoon/Gui/Layouts/Elements/LayoutDrawElement.cs, Splatoon/Serializables/Element.cs, Splatoon/Splatoon.cs
- Condition to have objects targeting you or not as drawpoints.
=> Adds "Target you" condition

Splatoon/Gui/Layouts/Elements/LayoutDrawElement.cs, Splatoon/Serializables/Element.cs, Splatoon/Utils/Gui.cs
- Fix OOB error when circles and cones were centered at 0,0,0
- Fix Cones being force filled
- Fix migration code to stop force filling everything
- Fix migration code to not migrate unfilled circles
=> Bug fixes for polygonal rendering

Splatoon/Gui/CGuiGeneralSettings.cs, Splatoon/Gui/OverlayGui.cs, Splatoon/Render/AutoClipZones.cs, Splatoon/Render/Renderer.cs, Splatoon/Serializables/Configuration.cs
Based on equivalent DelvUI functionality. Currently supported:
* Most windows
* Hot bars
* Cast bar
* Chat bubbles
* Party list
=> Support for automatically clipping some native UI elements

Splatoon/Gui/ClipZoneSelector.cs, Splatoon/Gui/OverlayGui.cs, Splatoon/Render/AutoClipZones.cs, Splatoon/Render/Renderer.cs, Splatoon/Splatoon.cs
- D3D buffer sizes were worryingly small, so increasing them for safety.
- Added a special debug log to try to debug an issue reported in Discord.
=> Increase D3D buffer sizes and add special debug log

Splatoon/Render/AutoClipZones.cs, Splatoon/Render/Renderer.cs
More auto clipping updates
- Hotbar buttons clipped individually to allow non-clipping around empty slots
- Enemy list added to the auto clips
=> Clip around individual buttons and enemy list

Splatoon/Render/AutoClipZones.cs
Added
* Main Target info health bar
* Statuses
* Parameter widget (HP and MP)
* Tweaked various others
=> Add more addons to AutoClipZones

Presets/Dawntrail content/Duties/Extreme - Everkeep.md
=> Everkeep - Extreme presets

SplatoonScripts/Generic/QuestHighlighter.cs
I wanted to track quest icons and objectives without having to leave TextAdvance enabled all the time, so I split this out and expanded upon it.
=> Add QuestHighlighter Script

Presets/Dawntrail content/Duties/Extreme - Worqor Lar Dor.md
Worqor Lar Dor - Extreme Presets
=> Worqor Lar Dor - Extreme Presets

Presets/Dawntrail/Dungeons/100 - The Strayborough Deadwalk.md
Modify Cup Spins to work with the Japanese client
=> Update 100 - The Strayborough Deadwalk.md

Splatoon/Gui/CGuiContribute.cs, Splatoon/Gui/CGuiRenderers.cs, Splatoon/LanguageChinese.ini, Splatoon/RenderEngines/RenderEngine.cs
Localization update of ChineseLanguage support to the new render tab
Localization update  many texts that were not previously updated
=> Localization update of ChineseLanguage

Splatoon/Gui/Layouts/Elements/LayoutDrawElement.cs, Splatoon/RenderEngines/DirectX11/DirectX11DisplayObjects.cs, Splatoon/RenderEngines/DirectX11/DirectX11Renderer.cs, Splatoon/RenderEngines/DirectX11/DirectX11Scene.cs, Splatoon/Serializables/CastAnimationKind.cs, Splatoon/Serializables/DisplayStyle.cs, Splatoon/Serializables/Element.cs, Splatoon/Utility/Colors.cs, Splatoon/Utility/ElementExtensions.cs, Splatoon/Utility/LayoutUtils.cs, SplatoonScripts/update.csv
Add option for DX11 renderer to choose one of three cast animations
=> Cast Animations

Splatoon/RenderEngines/DirectX11/DirectX11Scene.cs
Expose error message and lower stroke buffer size
=> Update pictomancy lib

SplatoonScripts/Duties/Dawntrail/R2S_Venom Love Pair Split.cs
It will memorize the chants for Venom Rain, Venom Drop, Love Rain, and Love Drop and display them during straight-line attacks and dynamo attacks.
=> Add R2S Pair and split show script

Presets/Dawntrail/Dungeons/100 - Tender Valley.md, Presets/Dawntrail/Raids/The Arcadion 2 Normal.md, Presets/Dawntrail/Raids/The Arcadion 3 Normal.md, Presets/Dawntrail/Raids/The Arcadion 4 Normal.md
- Added Barreltender to Tender Valley
- Verified International Triggers for Tender Valley and Normal Raids
=> Added support for several International Triggers

SplatoonScripts/Duties/Dawntrail/R1S Multiscript.cs
**R1S**
- Draws arrows indicating where soulshades will jump to
- Draws cleaves for One-Two Paw and Leaping One-Two Paw and when it is passed to the soulshades.
=> v1.0 R1S Multiscript

SplatoonScripts/Duties/Dawntrail/R1S Multiscript.cs
Removed OnCombatEnd() as it's not reliable and used OnReset() for cleanup
=> R1S Multiscript OnReset() Change

SplatoonScripts/Duties/Dawntrail/R1S Multiscript.cs
Missed flag resets for cloned one-two paw.
=> Missed flag resets

SplatoonScripts/Duties/Dawntrail/R1S Raining Cats.cs
fix Raining Cats script
- fixed the far and near decision to include tethers
=> Fix Raining Cats script

SplatoonScripts/Duties/Dawntrail/R1S Raining Cats.cs, SplatoonScripts/Duties/Dawntrail/R4S Electrope Edge.cs
Improve electrope edge script
- added Sidewise Spark
None/North/Inside/Side to choose freely according to roll.
=> Improve electrope edge script

Presets/Dawntrail/Raids/The Arcadion 1 Savage.md, Presets/Dawntrail/Raids/The Arcadion 4 Savage.md, Presets/Dawntrail/The Hunt/Mark Indicators.md
- Fixed grammar for Dawntrail hunt marks (e508191)
- Removed warning for M1S preset (e37e142)
- Removed warning for M4S script (b47c46b)
- Updated M4S Sunrise Sabbath script instructions for "resetting" it (b47c46b)
=> Preset updates

Presets/Dawntrail/Dungeons/100 - Alexandria.md
- Added Antivirus X cones
- Internationalized second boss, third boss was already international
=> Update 100 - Alexandria.md

SplatoonScripts/Duties/Endwalker/The Omega Protocol/Pantokrator invincible Reminder.cs
Omega's Pantokrator's final invincibility timing is troublesome to be aware of, so I created a script that counts down.
=> [add] TOP Script add

SplatoonScripts/Duties/Endwalker/The Omega Protocol/BSOD Adjuster.cs, SplatoonScripts/Generic/ScriptEventLogger.cs
This is a script for adjusting the P4 Phase. It does not take into account melee adjustments, but by setting it between the priorities, that is, 4th or 5th, it will be in charge of adjustments. The priority list is aligned from the top to the left.
I also improved the ScriptExplorer.
=> [add] TOP Script

SplatoonScripts/Duties/Endwalker/The Omega Protocol/Oversampled Wave Cannon.cs, SplatoonScripts/update.csv
We immediately used Garume's pull request for detection.
By turning it ON, you can force the character to face that direction and attack the enemy, eliminating mistakes due to the direction.
=> [add] Improvement Script

SplatoonScripts/Generic/ForceSetDirection.cs, SplatoonScripts/update.csv
I'm thinking of making a DSR scripts.
Could use it for that.
=> Add force set direction generic script

Presets/Dawntrail/Raids/The Arcadion 4 Savage.md
=> Added color description for Witch Hunt script

Presets/Shadowbringers/Duties/Ultimate - The Epic of Alexander.md
All of the TEA scripts were moved to a subfolder called "The Epic of Alexander" so I adjusted the URLs to the scripts accordingly. All links have been tested.
=> Update links for all TEA scripts

Splatoon/Memory/BuffEffectProcessor.cs, SplatoonScripts/Duties/Endwalker/The Omega Protocol/Beyond Defense.cs, SplatoonScripts/Duties/Endwalker/The Omega Protocol/P5 Delta Hello Guide.cs, SplatoonScripts/Generic/ScriptEventLogger.cs
Added a script to further strengthen the dynamisu delta gimmick script. During this process, the beyond diffence script was displayed at an unexpected time, so we made a correction.
I reflected the contents of what was said on pun.sh in Splatoon.
=> fix and add script, fix BuffEffectProcessor

Splatoon/Memory/BuffEffectProcessor.cs, Splatoon/SplatoonScripting/ScriptingProcessor.cs, Splatoon/SplatoonScripting/SplatoonScript.cs, Splatoon/Structures/RecordedStatus.cs, SplatoonScripts/Duties/Endwalker/The Omega Protocol/P5 Delta Hello Guide.cs, SplatoonScripts/Duties/Endwalker/The Omega Protocol/P6 MultiScript.cs, SplatoonScripts/Generic/ScriptEventLogger.cs, SplatoonScripts/Tests/OnBuffEffectTest.cs
I talked about this in a private chat. The buff name is now displayed in the log.
Also, I fixed a script error that was of concern.
=> fix script and Improvent Buff LogOutput

SplatoonScripts/Duties/Shadowbringers/The Epic Of Alexander/TEA P2 Nisi.cs, SplatoonScripts/Duties/Shadowbringers/The Epic Of Alexander/TEA P2 Temporal Stasis.cs, SplatoonScripts/Duties/Shadowbringers/The Epic Of Alexander/TEA_P2_Transition.cs
Added german language for players who neeeded it.
Nisi P2 is more common language and can be edited if you want it.
=> Added german language for TEA scripts

SplatoonScripts/Duties/Dawntrail/R2S Venom Love Pair Split.cs, SplatoonScripts/Duties/Dawntrail/R4S Chain Lightning.cs, SplatoonScripts/Duties/Dawntrail/R4S Witch Hunt.cs, SplatoonScripts/Duties/Endwalker/DSR Dooms.cs, SplatoonScripts/Duties/Endwalker/DSR Wrath.cs, SplatoonScripts/Duties/Endwalker/Dragonsong's Reprise/P2 Sanctity Of The Ward Second.cs, SplatoonScripts/Duties/Endwalker/Dragonsong's Reprise/P5 Death of the Heavens.cs, SplatoonScripts/Duties/Endwalker/Dragonsong's Reprise/P6 AutoTargetSwitcher.cs, SplatoonScripts/Duties/Endwalker/Dragonsong's Reprise/P6 Wroth Flames.cs, SplatoonScripts/Duties/Endwalker/P10S Tethers.cs, SplatoonScripts/Duties/Endwalker/P11S Multiscript.cs, SplatoonScripts/Duties/Endwalker/P12S Limit Cut.cs, SplatoonScripts/Duties/Endwalker/P12S Wing Cleaves.cs, SplatoonScripts/Duties/Endwalker/The Omega Protocol/BSOD Adjuster.cs, SplatoonScripts/Duties/Endwalker/The Omega Protocol/Cosmo Meteor Adjuster.cs, SplatoonScripts/Duties/Endwalker/The Omega Protocol/Dynamis Delta.cs, SplatoonScripts/Duties/Endwalker/The Omega Protocol/Hello World MoveGuide.cs, SplatoonScripts/Duties/Endwalker/The Omega Protocol/P5 Delta Hello Guide.cs, SplatoonScripts/Duties/Endwalker/The Omega Protocol/P6 MultiScript.cs, SplatoonScripts/Duties/Endwalker/The Omega Protocol/Party Synergy.cs, SplatoonScripts/Duties/Shadowbringers/The Epic Of Alexander/TEA P2 1211 Transition.cs, SplatoonScripts/Duties/Shadowbringers/The Epic Of Alexander/TEA P4 Fate Projection α.cs, SplatoonScripts/Duties/Shadowbringers/The Epic Of Alexander/TEA_P2_Transition.cs, SplatoonScripts/Duties/Stormblood/UCOB Tethers.cs, SplatoonScripts/Generic/ScriptEventLogger.cs
I would like to ask ARR or someone who is doing the testing to do it.
I fixed the build error.
=> [fix] Scripts 7.1 fixes

Presets/Dawntrail/Raids/Ultimate - The Futures Rewritten/Phase 2 - Usurper of Frost.md, SplatoonScripts/Duties/Dawntrail/The Futures Rewritten/P2 Light Rampant JP.cs, SplatoonScripts/Duties/Dawntrail/The Futures Rewritten/P2 Light Tempest JP.cs
Global support, but only Japanese settings are known
=> add jp light tempset

SplatoonScripts/Duties/Dawntrail/The Futures Rewritten/P2 Light Rampant.cs
Fixed this script that was sitting in SplatoonScripts.
Cleaned up comments, variables, and functions.
Tested with LesBin and NAUR strats, so an NA label would be appropriate. NAUR/Lesbin priority for this script is:
✔ North Swap 
`H1 H2 T1 T2 M2 M1 R2 R1`
=> Fix Redmoon's Light Rampant script

Presets/Dawntrail/Raids/Ultimate - The Futures Rewritten/Phase 2 - Usurper of Frost.md
Added the tested and working EU & NA Light Rampant script by Redmoon and Smoothtalk for NAUR (Lesbin) & LPDU starts
=> Update Phase 2 - Usurper of Frost.md

Presets/Stormblood/Duties/Ultimate - The Unending Coil of Bahamud.md, SplatoonScripts/Duties/Stormblood/UCOB Nael Quotes.cs
This script draws the unsafe zones for double and triple nael quotes.
=> UCOB P2: Add a script to handle nael quotes

SplatoonScripts/Duties/Dawntrail/The Futures Rewritten/P4 Darklit.cs
=> fix dark lit 

SplatoonScripts/Duties/Dawntrail/M5S Disco Infernal.cs
Refactored the shortdebuff exchange logic, fixed position swapping errors in melee roles, and implemented personalized optimizations to the rendering interface.
=> Fixed coordinate issues

SplatoonScripts/Duties/Dawntrail/M5S Disco Infernal raidplan.cs, SplatoonScripts/Duties/Dawntrail/M5S Disco Infernal.cs
While current usage is limited, retaining this implementation remains an operational necessity to accommodate edge cases and future-proof configuration compatibility.
=> Adapted the Raidplan strategy for minority adoption scenarios.

SplatoonScripts/Duties/Stormblood/UCOB Earthshakers.cs
Shows Earthshaker cones for QMT and TST
=> Add UCOB Earthshakers script

SplatoonScripts/Duties/Dawntrail/M8S Quad Beckon Moonlight JP Game 8.cs
Fix button conflict issue in debug mode
=> Update M8S Quad Beckon Moonlight JP Game 8.cs

Presets/Heavensward/Raids/Alexander 8 Savage.md
I put together some support for A8S. 
Initial Features include: 
- Megabeams from Onslaughter and Brute Justice
- Heights (A message will display underneath your character model of "Get High" or "Get Low")
- Transform: This is the P2 > P3 Transition. Draws a circle on where every party Ive ever joined goes for the KB and for healing
- Chakrams (Thank you @serenaeclipse from discord for this. I want to ensure I credit this appropriately)
- Apocalyptic Ray - Move right after super jump. The "Get Behind" mechanic.
=> Initial Support for A8S

SplatoonScripts/Duties/Endwalker/Dragonsong's Reprise/P5 Death of the Heavens.cs
Included configurations for dooms going N/S
=> Included both n/s doom locations

SplatoonScripts/Duties/Endwalker/The Omega Protocol/Program Loop Priority.cs
Removed light party dependent logic
=> Removed NAUR Specific logic, made universal for priority flexing

Presets/Dawntrail/Extreme Trials/EX5 - Necron's Embrace.md
No longer W.I.P. all mechanics that can be drawn are included.
"Relentless Reaping" will need a script
=> Update EX5 - Necron's Embrace.md
